# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock.proto',
  package='stp',
  syntax='proto3',
  serialized_pb=_b('\n\x0bstock.proto\x12\x03stp\"\xee\x01\n\tStockMeta\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12+\n\tstockType\x18\x02 \x01(\x0e\x32\x18.stp.StockMeta.StockType\x12\x13\n\x0bmarketIndex\x18\x03 \x01(\x05\x12\x15\n\rindustryIndex\x18\x04 \x01(\x05\x12\x14\n\x0c\x63onceptIndex\x18\x05 \x01(\x05\x12\x0e\n\x06totals\x18\x06 \x01(\x03\x12\x15\n\rearningRatios\x18\x07 \x01(\x02\"=\n\tStockType\x12\n\n\x06MARKET\x10\x00\x12\x0c\n\x08INDUSTRY\x10\x01\x12\x0b\n\x07\x43ONCEPT\x10\x02\x12\t\n\x05STOCK\x10\x03\"I\n\x0cStockElement\x12\x0f\n\x07needDay\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\x12\x0c\n\x04\x66lag\x18\x03 \x03(\x08\x12\x0c\n\x04line\x18\x04 \x01(\t\"\xa0\x02\n\x07StockDB\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x05\x12\x11\n\tstockSize\x18\x02 \x01(\x05\x12\x1d\n\x05metas\x18\x03 \x03(\x0b\x32\x0e.stp.StockMeta\x12,\n\x08\x65lements\x18\x04 \x03(\x0b\x32\x1a.stp.StockDB.ElementsEntry\x12\x30\n\nstockIndex\x18\x05 \x03(\x0b\x32\x1c.stp.StockDB.StockIndexEntry\x1a\x42\n\rElementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.stp.StockElement:\x02\x38\x01\x1a\x31\n\x0fStockIndexEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')
)



_STOCKMETA_STOCKTYPE = _descriptor.EnumDescriptor(
  name='StockType',
  full_name='stp.StockMeta.StockType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MARKET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDUSTRY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONCEPT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOCK', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=198,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_STOCKMETA_STOCKTYPE)


_STOCKMETA = _descriptor.Descriptor(
  name='StockMeta',
  full_name='stp.StockMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='stp.StockMeta.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stockType', full_name='stp.StockMeta.stockType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marketIndex', full_name='stp.StockMeta.marketIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='industryIndex', full_name='stp.StockMeta.industryIndex', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conceptIndex', full_name='stp.StockMeta.conceptIndex', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totals', full_name='stp.StockMeta.totals', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='earningRatios', full_name='stp.StockMeta.earningRatios', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STOCKMETA_STOCKTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=259,
)


_STOCKELEMENT = _descriptor.Descriptor(
  name='StockElement',
  full_name='stp.StockElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='needDay', full_name='stp.StockElement.needDay', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='stp.StockElement.data', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='stp.StockElement.flag', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line', full_name='stp.StockElement.line', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=334,
)


_STOCKDB_ELEMENTSENTRY = _descriptor.Descriptor(
  name='ElementsEntry',
  full_name='stp.StockDB.ElementsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stp.StockDB.ElementsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='stp.StockDB.ElementsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=574,
)

_STOCKDB_STOCKINDEXENTRY = _descriptor.Descriptor(
  name='StockIndexEntry',
  full_name='stp.StockDB.StockIndexEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stp.StockDB.StockIndexEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='stp.StockDB.StockIndexEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=625,
)

_STOCKDB = _descriptor.Descriptor(
  name='StockDB',
  full_name='stp.StockDB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='days', full_name='stp.StockDB.days', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stockSize', full_name='stp.StockDB.stockSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metas', full_name='stp.StockDB.metas', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elements', full_name='stp.StockDB.elements', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stockIndex', full_name='stp.StockDB.stockIndex', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STOCKDB_ELEMENTSENTRY, _STOCKDB_STOCKINDEXENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=625,
)

_STOCKMETA.fields_by_name['stockType'].enum_type = _STOCKMETA_STOCKTYPE
_STOCKMETA_STOCKTYPE.containing_type = _STOCKMETA
_STOCKDB_ELEMENTSENTRY.fields_by_name['value'].message_type = _STOCKELEMENT
_STOCKDB_ELEMENTSENTRY.containing_type = _STOCKDB
_STOCKDB_STOCKINDEXENTRY.containing_type = _STOCKDB
_STOCKDB.fields_by_name['metas'].message_type = _STOCKMETA
_STOCKDB.fields_by_name['elements'].message_type = _STOCKDB_ELEMENTSENTRY
_STOCKDB.fields_by_name['stockIndex'].message_type = _STOCKDB_STOCKINDEXENTRY
DESCRIPTOR.message_types_by_name['StockMeta'] = _STOCKMETA
DESCRIPTOR.message_types_by_name['StockElement'] = _STOCKELEMENT
DESCRIPTOR.message_types_by_name['StockDB'] = _STOCKDB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockMeta = _reflection.GeneratedProtocolMessageType('StockMeta', (_message.Message,), dict(
  DESCRIPTOR = _STOCKMETA,
  __module__ = 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stp.StockMeta)
  ))
_sym_db.RegisterMessage(StockMeta)

StockElement = _reflection.GeneratedProtocolMessageType('StockElement', (_message.Message,), dict(
  DESCRIPTOR = _STOCKELEMENT,
  __module__ = 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stp.StockElement)
  ))
_sym_db.RegisterMessage(StockElement)

StockDB = _reflection.GeneratedProtocolMessageType('StockDB', (_message.Message,), dict(

  ElementsEntry = _reflection.GeneratedProtocolMessageType('ElementsEntry', (_message.Message,), dict(
    DESCRIPTOR = _STOCKDB_ELEMENTSENTRY,
    __module__ = 'stock_pb2'
    # @@protoc_insertion_point(class_scope:stp.StockDB.ElementsEntry)
    ))
  ,

  StockIndexEntry = _reflection.GeneratedProtocolMessageType('StockIndexEntry', (_message.Message,), dict(
    DESCRIPTOR = _STOCKDB_STOCKINDEXENTRY,
    __module__ = 'stock_pb2'
    # @@protoc_insertion_point(class_scope:stp.StockDB.StockIndexEntry)
    ))
  ,
  DESCRIPTOR = _STOCKDB,
  __module__ = 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stp.StockDB)
  ))
_sym_db.RegisterMessage(StockDB)
_sym_db.RegisterMessage(StockDB.ElementsEntry)
_sym_db.RegisterMessage(StockDB.StockIndexEntry)


_STOCKDB_ELEMENTSENTRY.has_options = True
_STOCKDB_ELEMENTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_STOCKDB_STOCKINDEXENTRY.has_options = True
_STOCKDB_STOCKINDEXENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
